version: '3.7'

services:
  api:
    container_name: api
    user: root
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      proxy-net:
  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
          - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=lucas
      - POSTGRES_PASSWORD=zen777
      - POSTGRES_DB=wallaback
      - POSTGRES_HOST=localhost
    expose:
      - 5432
    networks:
      proxy-net:

networks:
  proxy-net:
volumes:
  postgres_data:
