version: '3.7'

services:
  api:
    container_name: api
    user: root
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    volumes:
      - data:/usr/src/data
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      proxy-net:
  db:
    container_name: Db
    image: postgres:12.0-alpine
    volumes:
          - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=lucas
      - POSTGRES_PASSWORD=zen777
      - POSTGRES_DB=wallaback
    expose:
      - 5432
    networks:
      proxy-net:

networks:
  proxy-net:
volumes:
  data:
  postgres_data:
