version: '2'
services:
  nginx:
    container_name: nginx
    restart: always
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./certs:/etc/nginx/certs:ro"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    networks:
      proxy-net:

  nginx-letsencrypt:
    container_name: ssl
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    depends_on:
      - nginx
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certs:/etc/nginx/certs:rw"
    networks:
      proxy-net:

  api:
    container_name: api
    user: root
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=wardixlab.com, www.wardixlab.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=wardixlab.com, www.wardixlab.com
      - LETSENCRYPT_EMAIL=resourceld@gmail.com
    depends_on:
      - db
    networks:
      proxy-net:

  db:
    container_name: db
    image: postgres:12.0-alpine
    user: postgres
    volumes:
          - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    expose:
      - 5432
    networks:
      proxy-net:
    depends_on:
      - nginx

networks:
  proxy-net:
volumes:
  postgres_data:
  certs:
  vhostd:
  config:
  html:
















